Repository Y-edu/Y-edu-front, pull requests merged in 2025-07, with the labels that each got.

#233 fix: 빌드오류 해결
  app/components/teacher/SessionList/RescheduleSheet.tsx
Labels: 🌍 Deploy

#234 fix: 구조 변경에 따른 타입 선언 수정
  app/components/teacher/SessionList/RescheduleSheet.tsx
Labels: 🐞BugFix

#232 fix: 어드민 매칭관리 탭 column 수정
  app/ui/Columns/ParentsColumns.tsx
Labels: 🐞BugFix

#236 fix: 카드 인덱스 3부터 과외완료 안되는 문제 수정
  app/(route)/(teacher)/teacher/session-complete/page.tsx
Labels: 🐞BugFix

#244 feat: 스크롤피커에서 위아래 옵션 터치로 선택 가능하도록 코드 추가
  app/ui/ScrollPicker/index.tsx
Labels: ✨ Feature

#246 fix: 수업관리 탭에 정규일정 노출
  app/actions/graphql/class-management.ts
  app/hooks/query/useGetClassList.ts
  app/ui/Columns/ClassColumns.tsx
Labels: 🐞BugFix
