Repository Y-edu/Y-edu-front, pull requests merged in 2025-04, with the labels that each got.

#119 Feat/teacher schedule setting / 로그인 페이지에 문구 추가, 오타 수정.
  app/components/teacher/TeacherSetting/TeacherSettingLogin.tsx
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
Labels: 💅 Style

#121 chore : 선생님 상담 결과 페이지 폴더 구조 생성
  app/(route)/(teacher)/result/[managementId]/page.tsx
Labels: ⚙️ Setting

#122 feat : 선생님 조율 결과 공유 페이지 퍼블리싱, 공통 컴포넌트 및 유틸 구현
  app/(route)/(teacher)/result/[managementId]/page.tsx
  app/(route)/globals.css
  app/(route)/layout.tsx
  app/components/result/ConfirmedResult.tsx
  app/components/result/DivWIthLabel.tsx
  app/components/result/FirstDayPicker.tsx
  app/components/result/HeaderWithBack.tsx
  app/components/result/OnBoarding.tsx
  app/components/result/RejectedResult.tsx
  app/components/result/TimePicker.tsx
  app/hooks/custom/useDOMRef.ts
  app/icons/IconCheck.tsx
  app/icons/IconDown.tsx
  app/icons/IconLeft.tsx
  app/icons/IconWarning.tsx
  app/types/react.ts
  app/ui/BottomSheet/index.tsx
  app/ui/Button/index.tsx
  app/ui/Button/useButton.ts
  app/ui/CheckBox/index.tsx
  app/ui/Textarea/index.tsx
  app/utils/cn.ts
  package.json
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature

#125 feat: 선생님 스케줄 조율 결과 화면 및 기능 구현
  app/(route)/(teacher)/result/[managementId]/page.tsx
  app/actions/delete-schedule/index.ts
  app/actions/put-schedule/index.ts
  app/components/result/ConfirmedResult.tsx
  app/components/result/ConfirmedResult/index.tsx
  app/components/result/ConfirmedResult/useConfirmedResult.ts
  app/components/result/DayBtn.tsx
  app/components/result/DivWIthLabel.tsx
  app/components/result/FirstDayPicker.tsx
  app/components/result/FirstDayPicker/index.tsx
  app/components/result/FirstDayPicker/useFirstDayPicker.ts
  app/components/result/OnBoarding.tsx
  app/components/result/RejectedResult.tsx
  app/components/result/SelectButton.tsx
  app/components/result/TimePicker.tsx
  app/components/result/TimePicker/index.tsx
  app/components/result/TimePicker/useTimePicker.ts
  app/hooks/mutation/useDeleteSchedule.ts
  app/hooks/mutation/usePutSchedule.ts
  app/ui/BottomSheet/index.tsx
  app/ui/Button/useButton.ts
  app/ui/CheckBox/index.tsx
  app/ui/ScrollPicker/index.tsx
  app/utils/httpService.ts
Labels: ✨ Feature, 🛠️ Refactor

#126 Feat/add schedule result : 학부모 매칭 리스트 및 요청사항 탭에 상담 결과 수업 요일,시간 추가
  app/actions/get-parents-list/index.ts
  app/actions/get-parents-request/index.ts
  app/components/admin/ParentsRequest.tsx
  app/constants/parentsRequest.ts
  app/ui/Columns/ParentsColumns.tsx
Labels: ✨ Feature, 💅 Style

#128 Feat/submitted result page : 제출된 페이지 컴포넌트 추가 및 라우팅 로직 변경
  app/(route)/(teacher)/result/[managementId]/page.tsx
  app/actions/get-matching-schedule/index.ts
  app/components/admin/AlimColumn.tsx
  app/components/result/ConfirmedResult/useConfirmedResult.ts
  app/components/result/FirstDayPicker/useFirstDayPicker.ts
  app/components/result/RejectedResult.tsx
  app/components/result/SubmittedResult.tsx
  app/hooks/query/useGetMatchingSchedule.ts
  public/images/Letter.svg
Labels: ✨ Feature, 💅 Style

#130 Fix/schedule byunghoon qa : 병훈 QA
  app/(route)/(admin)/zuzuclubadmin/[id]/(hooks)/useAlimTable.tsx
  app/(route)/(teacher)/result/[managementId]/page.tsx
  app/components/result/ConfirmedResult/useConfirmedResult.ts
  app/components/result/RejectedResult.tsx
  app/ui/ScrollPicker/index.tsx
Labels: 🐞BugFix, 💅 Style

#132 Fix/schedule byunghoon qa2 : 롤플레잉 QA 진행 후 일부 수정
  app/actions/get-parents-request/index.ts
  app/components/admin/ParentsRequest.tsx
  app/components/admin/TeacherListSearch.tsx
  app/components/result/ConfirmedResult/index.tsx
  app/components/result/FirstDayPicker/index.tsx
  app/components/result/FirstDayPicker/useFirstDayPicker.ts
  app/components/result/OnBoarding.tsx
  app/constants/parentsRequest.ts
  app/ui/ScrollPicker/index.tsx
  app/utils/formatFirstClassInfo.ts
Labels: ✨ Feature, 💅 Style

#136 feat: 결과 페이지 구현
  .eslintrc.json
  app/(route)/(common)/layout.tsx
  app/(route)/(common)/result/page.tsx
  app/constants/result/resultImg.ts
  app/data/teacherDetailClass.json
  app/data/teacherDetailMain.json
  app/data/teacherProfile.json
  app/ui/Result.tsx
Labels: ✨ Feature

#138 Feat/timetable multi page support : 타임테이블 커스텀훅 모드 분리, 학부모 모드 훅 코드 작업
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TimeTable/index.tsx
  app/components/teacher/TimeTable/useTimeTable.ts
  app/icons/IconWarning.tsx
  app/ui/Snackbar/index.tsx
Labels: ✨ Feature, 🛠️ Refactor

#139 Feat/TimeTable 가이드 오버레이 구현
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TimeTable/GuideTimeTable.tsx
  app/constants/result/resultImg.ts
  package.json
  public/images/finger-tap.svg
  yarn.lock
Labels: ✨ Feature

#142 Feat/timetable multi page support : 학부모 시간선택 타임테이블 페이지 코드 작업 및 usTimeTable 커스텀훅 오류 수정 등
  app/actions/get-acceptance/index.ts
  app/actions/get-parents-request/index.ts
  app/actions/post-matching-timetable/index.ts
  app/components/admin/AlimColumn.tsx
  app/components/teacher/TeacherDetail/TeacherDetailChooseTime.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TimeTable/index.tsx
  app/components/teacher/TimeTable/useTimeTable.ts
  app/hooks/mutation/usePostMatchingTimeTable.ts
  app/ui/Snackbar/index.tsx
  next.config.mjs
Labels: 🐞BugFix, ⚙️ Setting, ✨ Feature, 🛠️ Refactor, 💅 Style

#141 feat/선생님 시간 설정 알림톡 경로 접근 시 토큰으로 로그인 처리
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
Labels: ✨ Feature

#144 fix: Type 관련 빌드 오류 해결
  app/(route)/(admin)/zuzuclubadmin/[id]/(hooks)/useAlimTable.tsx
  app/components/admin/ParentsRequest.tsx
Labels: 🐞BugFix, 🚨 Hotfix

#143 feat: 과외 수락/거절 페이지 + 학부모 선생님 선택 페이지(선생님 상세 페이지) 라우팅 수정
  app/(route)/(common)/layout.tsx
  app/(route)/(teacher)/teacher/[id]/TeacherPage.tsx
  app/(route)/(teacher)/teacher/[id]/layout.tsx
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/(route)/(teacher)/teacher/notify/[token]/complete/page.tsx
  app/(route)/(teacher)/teacher/notify/[token]/page.tsx
  app/(route)/(teacher)/teacher/notify/[token]/select-time/page.tsx
  app/(route)/(teacher)/teacher/recommend/[token]/complete/page.tsx
  app/(route)/(teacher)/teacher/recommend/[token]/page.tsx
  app/(route)/(teacher)/teacher/recommend/[token]/select-time/page.tsx
  app/actions/get-teacher-all-detail/index.ts
  app/actions/get-tutoring/index.ts
  app/actions/post-tutoring-accept/index.ts
  app/actions/post-tutoring-refuse/index.ts
  app/components/teacher/MatchingInfo.tsx
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/ProfileTop.tsx
  app/components/teacher/TeacherDetail/TeacherDetailClass.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
  app/hooks/query/useGetTeacherAllDetails.ts
  app/hooks/query/useGetTutoringDetail.ts
  app/store/teacher/recommend/useRecommendStore.ts
  app/utils/formatDayTimes.ts
Labels: 🐞BugFix, ✨ Feature, 🛠️ Refactor

#146 Feat/Fix/선생님-타임테이블-업데이트
  app/actions/get-teacher-all-detail/index.ts
  app/actions/put-teacher-available/index.ts
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TimeTable/useTimeTable.ts
  app/hooks/mutation/usePutAvailableTeacherTime.ts
Labels: 🐞BugFix, ✨ Feature

#147 Feat/timetable multi page support : 매칭 수락/거절 페이지의 타임테이블 api 연결 및 분기,예외처리 코드 작업, 학부모 타임테이블 코드작업
  app/(route)/(teacher)/teacher/notify/[token]/select-time/page.tsx
  app/(route)/(teacher)/teacher/recommend/[token]/select-time/page.tsx
  app/actions/get-tutoring/index.ts
  app/components/teacher/MatchingInfo.tsx
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/TeacherDetail/TeacherDetailChooseTime.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TimeTable/useTimeTable.ts
  app/store/teacher/recommend/useRecommendStore.ts
Labels: 🐞BugFix, ✨ Feature

#148 Feat/TabBar 스크롤 모드추가
  app/(route)/(teacher)/teacher/recommend/[token]/page.tsx
  app/ui/Bar/TabBar.tsx
Labels: ✨ Feature

#149 Feat/timetable multi page support : 버튼 디자인 수정, 알림톡 테이블 상태값 순서 변경.
  app/(route)/(admin)/zuzuclubadmin/[id]/(hooks)/useAlimTable.tsx
  app/components/teacher/TeacherDetail/TeacherDetailChooseTime.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
Labels: 💅 Style

#153 Feat/timetable multi page support : 병훈 QA
  app/(route)/(teacher)/teacher/notify/[token]/select-time/page.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TimeTable/useTimeTable.ts
  app/hooks/query/useGetTutoringDetail.ts
  app/ui/Snackbar/index.tsx
Labels: 🐞BugFix, 💅 Style

#154 fix: 기능 QA 수정 (혜원)
  app/(route)/(teacher)/teacher/notify/[token]/select-time/page.tsx
  app/(route)/(teacher)/teacher/sample/page.tsx
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/ui/Modal.tsx
Labels: 🐞BugFix

#156 feat: tally 링크 임베딩
  app/(route)/(parents)/form/page.tsx
  app/(route)/(teacher)/layout.tsx
Labels: ✨ Feature

#157 feat: 사용자 행동 분석을 위한 GA, 태그매니저 이식
  app/(route)/(parents)/form/page.tsx
  app/(route)/layout.tsx
  package.json
  yarn.lock
Labels: ✨ Feature

#158 fix: teacher/[id] 페이지 추가 + UX 문구 수정
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/actions/get-teacher-detail/index.ts
  app/components/teacher/TeacherDetail/TeacherDetailChooseTime.tsx
  app/hooks/query/useGetTeacherDetails.ts
Labels: 🐞BugFix

#159 Feat/timetable multi page support : 병훈 QA
  app/(route)/(teacher)/teacher/notify/[token]/select-time/page.tsx
  app/actions/get-tutoring/index.ts
  app/components/admin/AlimMatchCell.tsx
  app/components/result/ConfirmedResult/useConfirmedResult.ts
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
Labels: 🐞BugFix, 💅 Style

#160 style: TeacherDetail css 수정
  app/components/teacher/TeacherDetail/TeacherDetailClass.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/ui/Bar/TabBar.tsx
Labels: 💅 Style

#161 fix: 타임테이블 영역 스크롤 할 때 셀도 함께 클릭되는 문제 해결
  app/components/teacher/TimeTable/index.tsx
Labels: 🐞BugFix
