Repository Y-edu/Y-edu-front, pull requests merged in 2025-02, with the labels that each got.

#32 Feature/ 특정 과외 수락/거절 용 MatchingProposal컴포넌트 구현
  __mocks__/handler.ts
  __mocks__/matching.ts
  app/actions/get-tutoring/index.ts
  app/actions/post-tutoring-accept/index.ts
  app/actions/post-tutoring-refuse/index.ts
  app/components/teacher/IconTitleChip.tsx
  app/components/teacher/MatchingInfo.tsx
  app/components/teacher/MatchingModal.tsx
  app/components/teacher/MatchingProposal.tsx
  app/hooks/mutation/usePostTutoringAccept.ts
  app/hooks/mutation/usePostTutoringRefuse.ts
  app/hooks/query/index.ts
  app/hooks/query/useGetTutoringDetail.ts
Labels: ✨ Feature

#33 Style: 특정 과외 신청/거절 스타일 추가
  app/components/teacher/IconTitleChip.tsx
  app/components/teacher/MatchingInfo.tsx
  app/components/teacher/MatchingModal.tsx
  app/components/teacher/MatchingProposal.tsx
  public/images/ModalClose.svg
Labels: 💅 Style

#34 feat: 선생님 상세 페이지 완성
  app/(route)/(teacher)/teacher/[id]/layout.tsx
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/components/root/TeacherListFilter.tsx
  app/components/teacher/IconTitleChip.tsx
  app/components/teacher/ProfileImageName.tsx
  app/components/teacher/ProfileInfoBox.tsx
  app/components/teacher/ProfileTop.tsx
  app/components/teacher/TeacherDetail/TeacherDetailClass.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
  app/data/teacherProfile.json
  app/ui/Bar/Sidebar.tsx
  app/ui/Bar/TabBar.tsx
  app/ui/Filter/CategoryFilter.tsx
  app/ui/Filter/RegionFilter.tsx
  app/ui/List/BulletList.tsx
  app/ui/List/DividerList.tsx
  app/ui/ToggleBox.tsx
  app/ui/index.ts
  public/images/arrow-light.png
  public/images/person-img.png
  tailwind.config.js
Labels: ✨ Feature

#35 Feat/teacher list filter refactor : 필터 상태관리 코드 리팩토링, 현재 필터 상태 마크업 및 기능 추가, 테이블 Style 통일 등
  __mocks__/teacherList.ts
  app/actions/patch-teacherModal/index.ts
  app/components/root/AlimTable.tsx
  app/components/root/Teacher.tsx
  app/components/root/TeacherList.tsx
  app/components/root/TeacherListFilter.tsx
  app/components/root/TeacherListSearch.tsx
  app/types/TeacherFilters.ts
  app/ui/Columns/TeacherColumns.tsx
  app/ui/EditTeacherModal.tsx
  app/ui/Filter/RegionFilter.tsx
  public/images/youtube-red.svg
Labels: ✨ Feature, 🛠️ Refactor, 💅 Style

#36 feat: 선생님 상세 페이지 api 연동
  .gitignore
  app/(route)/(teacher)/layout.tsx
  app/actions/get-teacher-detail/index.ts
  app/components/teacher/IconTitleChip.tsx
  app/components/teacher/MatchingModal.tsx
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/ProfileTop.tsx
  app/components/teacher/TeacherDetail/TeacherDetailClass.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
  app/hooks/query/useGetTeacherDetails.ts
  app/ui/List/BulletList.tsx
  app/ui/List/DividerList.tsx
  app/ui/ToggleBox.tsx
  app/utils/formatAvailableTimes.ts
  app/utils/httpService.ts
  next.config.mjs
Labels: ⚙️ Setting, ✨ Feature

#38 Style: 특정과외 신청 건 디자인 수정
  app/components/teacher/MatchingModal.tsx
  app/components/teacher/MatchingProposal.tsx
Labels: 💅 Style

#40 Feat/parents list api : [어드민] 학부모 리스트 테이블 데이터 api 연동 완료
  app/actions/get-parents-list/index.ts
  app/actions/put-parent-status-toggle/index.ts
  app/components/root/ParentsList.tsx
  app/hooks/mutation/usePutParentStatusToggle.ts
  app/hooks/query/useGetParentsList.ts
  app/ui/Columns/ParentsColumns.tsx
Labels: ✨ Feature

#41 feat: admin kakaoName,매칭 조회 api 연결
  app/(route)/(admin)/[id]/(hooks)/useAlimTable.tsx
  app/(route)/(admin)/[id]/page.tsx
  app/(route)/layout.tsx
  app/actions/get-acceptance/index.ts
  app/actions/get-matching/index.ts
  app/actions/get-parents-request/index.ts
  app/actions/patch-displayname/index.ts
  app/components/root/AlimColumn.tsx
  app/components/root/AlimHeader.tsx
  app/components/root/ParentsRequest.tsx
  app/hooks/query/useGetParentsRequest.ts
  app/ui/Header.tsx
Labels: ✨ Feature

#44 Feat/teacher list filter api
  app/(route)/(admin)/[id]/page.tsx
  app/actions/get-teacher-search/index.ts
  app/actions/patch-teacher-Issue/index.ts
  app/components/root/Teacher.tsx
  app/components/root/TeacherList.tsx
  app/components/root/TeacherListFilter.tsx
  app/components/root/TeacherListSearch.tsx
  app/constants/filterData.ts
  app/hooks/custom/useEditTeacherModal.ts
  app/hooks/mutation/usePatchTeacherIssue.ts
  app/hooks/query/useGetParentsRequest.ts
  app/hooks/query/useGetTeacherSearch.ts
  app/types/ParentsList.ts
  app/types/TeacherFilters.ts
  app/types/TeacherProfile.ts
  app/ui/Columns/TeacherColumns.tsx
  app/ui/Filter/CategoryFilter.tsx
  app/ui/Filter/RegionFilter.tsx
  app/ui/TeacherIssueModal.tsx
Labels: ✨ Feature, 🛠️ Refactor, 💅 Style

#47 Feature : 알림톡 발송, 추가발송 API 연결 및 query-devtools 추가
  app/actions/post-acceptance/index.ts
  app/actions/post-new-acceptance/index.ts
  app/components/root/AlimHeader.tsx
  app/components/root/TeacherListSearch.tsx
  app/hooks/query/useGetAcceptance.ts
  app/providers/QueryProvider.tsx
  package.json
  yarn.lock
Labels: ✨ Feature

#48 feature : 매칭 리스트 부분에 페이지네이션 추가
  app/components/root/ParentsList.tsx
Labels: ✨ Feature

#45 Feat/login : 로그인 페이지 마크업 및 기능구현
  app/(route)/(admin)/layout.tsx
  app/(route)/(admin)/login/page.tsx
  app/actions/get-auth/get-login/index.ts
  app/actions/get-auth/get-logout/index.ts
  app/actions/get-auth/get-regenerate/index.ts
  app/components/auth/login.tsx
  app/hooks/auth/useLogin.ts
  app/hooks/auth/useLogout.ts
  app/hooks/auth/useRegenerate.ts
  app/hooks/auth/useRequireAuth.ts
  app/store/auth/useAuthStore.ts
  app/ui/Bar/Sidebar.tsx
Labels: ✨ Feature

#49 Feat/teacher list filter api : 필터에 '그외학교' 추가 / 유튜브 링크입력 api 연동
  app/actions/get-teacher-search/index.ts
  app/actions/patch-teacher-video/index.ts
  app/components/root/TeacherList.tsx
  app/components/root/TeacherListFilter.tsx
  app/hooks/mutation/usePatchTeacherVideo.ts
  app/ui/Columns/TeacherColumns.tsx
  app/ui/EditTeacherModal.tsx
  app/ui/TeacherIssueModal.tsx
  app/ui/TeacherUpdateModal.tsx
  yarn.lock
Labels: ✨ Feature

#51 feat : api 요청 헤더에 인증토큰 추가
  app/actions/get-auth/get-regenerate/index.ts
  app/actions/get-teacher-search/index.ts
  app/actions/patch-teacher-Issue/index.ts
  app/actions/patch-teacher-video/index.ts
  app/utils/httpService.ts
Labels: ✨ Feature

#52 refactor: 폴더구조 변경 (admin 하위 폴더로 추가)
  __tests__/example.test.tsx
  app/(route)/(admin)/page.tsx
  app/(route)/(admin)/zuzuclubadmin/[id]/(hooks)/useAlimTable.tsx
  app/(route)/(admin)/zuzuclubadmin/[id]/page.tsx
  app/(route)/(admin)/zuzuclubadmin/layout.tsx
  app/(route)/(admin)/zuzuclubadmin/login/page.tsx
  app/(route)/(admin)/zuzuclubadmin/page.tsx
  app/(route)/(admin)/zuzuclubadmin/settle-management/page.tsx
  app/(route)/(admin)/zuzuclubadmin/teacher-management/page.tsx
  app/(route)/page.tsx
  app/components/admin/Alim.tsx
  app/components/admin/AlimColumn.tsx
  app/components/admin/AlimHeader.tsx
  app/components/admin/AlimTable.tsx
  app/components/admin/ParentsList.tsx
  app/components/admin/ParentsRequest.tsx
  app/components/admin/Teacher.tsx
  app/components/admin/TeacherList.tsx
  app/components/admin/TeacherListFilter.tsx
  app/components/admin/TeacherListSearch.tsx
  app/components/auth/login.tsx
  app/components/root/main.tsx
  app/ui/Bar/Sidebar.tsx
  public/images/y-edu-logo.png
Labels: 🛠️ Refactor

#53 feat: 선생님 수락/보류 페이지 url 지정 + 선생님 상세 페이지 유튜브 영상 임베드 구현 + 메타데이터 변경
  app/(route)/(teacher)/teacher/[id]/[formId]/[phone]/page.tsx
  app/(route)/layout.tsx
  app/actions/get-teacher-detail/index.ts
  app/components/teacher/ProfileImageName.tsx
  app/components/teacher/TeacherDetail/TeacherDetailClass.tsx
  app/favicon.ico
  app/hooks/custom/useEditTeacherModal.ts
  app/utils/getYoutubeEmbedLink.ts
Labels: ✨ Feature, 🛠️ Refactor, 🌍 Deploy

#54 fix: 선생님 수락/보류 페이지 세부 멘트 + 스타일 디테일 수정
  app/(route)/(admin)/zuzuclubadmin/settle-management/page.tsx
  app/(route)/globals.css
  app/components/teacher/MatchingInfo.tsx
  app/components/teacher/MatchingModal.tsx
  app/components/teacher/MatchingProposal.tsx
Labels: 🐞BugFix, 💅 Style

#56 fix: 선생님 상세 페이지 + 선생님 수락/보류 페이지 위주 QA 버그 픽스
  app/components/teacher/MatchingInfo.tsx
  app/components/teacher/MatchingModal.tsx
  app/components/teacher/ProfileImageName.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/utils/formatAvailableTimes.ts
Labels: 🐞BugFix, 💅 Style

#57 Fix/byunghoon qa : 병훈 담당 QA 작업
  app/(route)/(admin)/zuzuclubadmin/[id]/(hooks)/useAlimTable.tsx
  app/actions/get-teacher-search/index.ts
  app/components/admin/AlimHeader.tsx
  app/components/admin/AlimTable.tsx
  app/components/admin/ParentsList.tsx
  app/components/admin/ParentsRequest.tsx
  app/components/admin/Teacher.tsx
  app/components/admin/TeacherList.tsx
  app/components/admin/TeacherListSearch.tsx
  app/favicon.ico
  app/hooks/custom/useGetSelectedTeacherNickname.ts
  app/ui/Columns/ParentsColumns.tsx
  app/ui/Columns/TeacherColumns.tsx
  app/ui/Modal.tsx
  app/utils/calculateMonthlyFee.ts
Labels: 🐞BugFix, 💅 Style

#58 Fix/byunghoon qa : classTime,classCount 타입 수정 및 format util 코드 적용.
  app/actions/get-parents-list/index.ts
  app/actions/get-parents-request/index.ts
  app/components/admin/ParentsRequest.tsx
  app/ui/Columns/ParentsColumns.tsx
  app/utils/calculateMonthlyFee.ts
  app/utils/formatMonthlyFee.ts
Labels: 🐞BugFix, 🛠️ Refactor

#59 fix: 과외 수락/보류 페이지 오류 해결 + 선생님 상세페이지 Error 처리
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/actions/get-tutoring/index.ts
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/ProfileTop.tsx
  app/components/teacher/TeacherDetail/TeacherDetailClass.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
  app/ui/ErrorUI.tsx
  package.json
  tailwind.config.js
  yarn.lock
Labels: 🐞BugFix

#60 fix: 선생님 상세 페이지 + 선생님 수락/보류 페이지 QA 오류 해결
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/ProfileInfoBox.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/hooks/query/useGetTeacherDetails.ts
Labels: 🐞BugFix, 💅 Style

#61 fix: 선생님 수락/보류 페이지 오류 처리 + 각종 null 처리 추가
  app/(route)/(teacher)/teacher/[id]/[formId]/[phone]/page.tsx
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/TeacherDetail/TeacherDetailClass.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
  app/hooks/query/useGetTutoringDetail.ts
Labels: 🐞BugFix

#62 fix : 디자인 qa 사항 반영
  app/components/teacher/MatchingModal.tsx
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/ProfileInfoBox.tsx
Labels: 💅 Style

#63 style: 각종 페이지 글자 색상 변경 + 아이콘 이미지 변경
  app/components/teacher/IconTitleChip.tsx
  app/components/teacher/MatchingInfo.tsx
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/ProfileInfoBox.tsx
  public/images/Assist.png
  public/images/Layers.png
  public/images/Listen.png
  public/images/Read.png
  public/images/Speak.png
  public/images/Talk.png
Labels: 💅 Style

#64 refactor : 수업료 필드 추가
  app/actions/get-tutoring/index.ts
  app/components/teacher/MatchingInfo.tsx
  app/components/teacher/MatchingProposal.tsx
Labels: 🛠️ Refactor

#66 fix: 카카오아이디 입력란 디폴트값 제거, placeHolder 추가, 스타일 조정
  app/ui/Header.tsx
Labels: 💅 Style

#67 chore : 절대 경로 설정
  .eslintrc.json
  app/(route)/(admin)/zuzuclubadmin/[id]/(hooks)/useAlimTable.tsx
  app/(route)/(admin)/zuzuclubadmin/[id]/page.tsx
  app/(route)/(admin)/zuzuclubadmin/layout.tsx
  app/(route)/(admin)/zuzuclubadmin/login/page.tsx
  app/(route)/(admin)/zuzuclubadmin/page.tsx
  app/(route)/(teacher)/teacher/[id]/[formId]/[phone]/page.tsx
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/(route)/page.tsx
  app/actions/get-acceptance/index.ts
  app/actions/get-auth/get-login/index.ts
  app/actions/get-auth/get-logout/index.ts
  app/actions/get-auth/get-regenerate/index.ts
  app/components/admin/AlimColumn.tsx
  app/components/admin/AlimHeader.tsx
  app/components/admin/AlimTable.tsx
  app/components/admin/ParentsList.tsx
  app/components/admin/ParentsRequest.tsx
  app/components/admin/Teacher.tsx
  app/components/admin/TeacherList.tsx
  app/components/admin/TeacherListFilter.tsx
  app/components/admin/TeacherListSearch.tsx
  app/hooks/auth/useLogin.ts
  app/hooks/auth/useLogout.ts
  app/hooks/auth/useRegenerate.ts
  app/hooks/auth/useRequireAuth.ts
  app/hooks/mutation/usePatchMatchingDisplayname.ts
  app/hooks/mutation/usePatchTeacherIssue.ts
  app/hooks/mutation/usePatchTeacherModal.ts
  app/hooks/mutation/usePatchTeacherVideo.ts
  app/hooks/mutation/usePostMatchingAcceptance.ts
  app/hooks/mutation/usePostNewMatchingAcceptance.ts
  app/hooks/mutation/usePostTutoringAccept.ts
  app/hooks/mutation/usePostTutoringRefuse.ts
  app/hooks/mutation/usePutParentStatusToggle.ts
  app/hooks/query/useGetAcceptance.ts
  app/hooks/query/useGetMatchingInfo.ts
  app/hooks/query/useGetParentsRequest.ts
  app/hooks/query/useGetTeacherSearch.ts
  app/hooks/query/useGetTeachers.ts
  app/hooks/query/useGetTutoringDetail.ts
  app/ui/Columns/ParentsColumns.tsx
  app/ui/Columns/TeacherColumns.tsx
  app/ui/TeacherUpdateModal.tsx
  app/utils/formatAvailableTimes.ts
  app/utils/httpService.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: ⚙️ Setting

#68 fix : 선생님 프로필 불가 -> 아예 보이지 않도록 수정
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
  app/hooks/query/useGetTeacherDetails.ts
  app/utils/formatAvailableTimes.ts
Labels: 🚨 Hotfix, 🛠️ Refactor

#71 feat : 학부모 상세 정보 -> 원하는 시간 필드 추가
  app/actions/get-parents-request/index.ts
  app/components/admin/ParentsRequest.tsx
  app/constants/parentsRequest.ts
  app/hooks/query/useGetParentsRequest.ts
Labels: ✨ Feature

#70 Fix/byunghoon qa : 어드민에서 선생님 프로필 상세보기로 가는 기능 추가, 링크에따른 사이드바 스타일 적용 방식 변경'
  app/(route)/(admin)/zuzuclubadmin/[id]/page.tsx
  app/actions/get-acceptance/index.ts
  app/components/admin/AlimColumn.tsx
  app/ui/Bar/Sidebar.tsx
  app/ui/Columns/TeacherColumns.tsx
Labels: ✨ Feature, 💅 Style

#72 chore : 절대경로 규칙 린트로 강제하기
  .eslintrc.json
  __tests__/example.test.tsx
  app/(route)/layout.tsx
  app/actions/get-matching/index.ts
  app/actions/get-parents-list/index.ts
  app/actions/get-parents-request/index.ts
  app/actions/get-teacher-detail/index.ts
  app/actions/get-teacher-search/index.ts
  app/actions/get-teachers/index.ts
  app/actions/get-tutoring/index.ts
  app/actions/patch-displayname/index.ts
  app/actions/patch-teacher-Issue/index.ts
  app/actions/patch-teacher-video/index.ts
  app/actions/patch-teacherModal/index.ts
  app/actions/post-acceptance/index.ts
  app/actions/post-new-acceptance/index.ts
  app/actions/post-tutoring-accept/index.ts
  app/actions/post-tutoring-refuse/index.ts
  app/actions/put-parent-status-toggle/index.ts
  app/components/admin/Alim.tsx
  app/components/auth/login.tsx
  app/components/teacher/MatchingInfo.tsx
  app/components/teacher/MatchingModal.tsx
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/ProfileTop.tsx
  app/components/teacher/TeacherDetail/TeacherDetailClass.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
  app/constants/goalsIconMapping.ts
  app/constants/teacherStyle.ts
  app/hooks/custom/useEditTeacherModal.ts
  app/hooks/custom/useGetSelectedTeacherNickname.ts
  app/hooks/query/useGetParentsList.ts
  app/ui/Bar/Sidebar.tsx
  app/ui/Filter/RegionFilter.tsx
  app/ui/Header.tsx
  app/ui/Modal.tsx
  app/ui/ToggleBox.tsx
  package.json
  yarn.lock
Labels: ⚙️ Setting

#73 fix: 선생님 리스트에서 해당 매칭건의 알람톡 발송된 선생님 검색 제외
  app/actions/get-teacher-search/index.ts
  app/components/admin/Teacher.tsx
  app/components/admin/TeacherList.tsx
  app/hooks/query/useGetTeacherSearch.ts
Labels: ✨ Feature

#78 feat:우수 프로필 선생님 추가
  app/(route)/(teacher)/teacher/[id]/[formId]/[phone]/page.tsx
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/(route)/(teacher)/teacher/sample/page.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
  public/images/exampleProfile.jpeg
Labels: ⚙️ Setting

#76 feature : 선생님 정보 탭 초기 로딩 속도를 위한 개선
  app/(route)/(teacher)/teacher/[id]/TeacherPage.tsx
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/actions/get-teacher-detail/index.ts
  app/components/teacher/TeacherDetail/TeacherDetailClass.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
  app/utils/getQueryClient.ts
Labels: ✨ Feature

#81 Fix/byunghoon qa : 선생님 프로필 샘플 페이지에서 선호시간 영역 렌더링 안되는 오류 해결.
  app/(route)/(teacher)/teacher/sample/page.tsx
Labels: 🐞BugFix

#82 Develop to Main
  app/(route)/(teacher)/teacher/sample/page.tsx
  app/actions/get-acceptance/index.ts
  app/actions/get-teacher-search/index.ts
  app/components/admin/AlimColumn.tsx
  app/ui/Columns/TeacherColumns.tsx
Labels: 🌍 Deploy

#83 fix : 우수 프로필 사례 정적 내용 수정
  app/(route)/(teacher)/teacher/sample/page.tsx
Labels: 💅 Style

#85 Fix/byunghoon qa : 선생님 관리 탭에 선생님 리스트 컴포넌트 추가.
  app/(route)/(admin)/zuzuclubadmin/teacher-management/page.tsx
  app/ui/Bar/Sidebar.tsx
Labels: ✨ Feature, 💅 Style

#88 add: 협의하여 시간 조율 가능 문구 추가
  app/components/teacher/MatchingProposal.tsx
  app/components/teacher/TeacherDetail/TeacherDetailRegionTime.tsx
Labels: 💅 Style
