Repository Y-edu/Y-edu-front, pull requests merged in 2025-01, with the labels that each got.

#4 docs: PR 템플릿 작성
  .github/pull_request_template.md
Labels: 📜 Docs

#6 feat: 사이드바 컴포넌트 구현
  app/(route)/layout.tsx
  app/(route)/page.tsx
  app/(route)/settle-management/page.tsx
  app/(route)/teacher-management/page.tsx
  app/ui/Sidebar.tsx
  app/ui/index.ts
  public/images/logo.png
Labels: 💅 Style

#9 chore:tailwind 전역 색상 변수 추가
  app/ui/Sidebar.tsx
  tailwind.config.js
Labels: 💅 Style

#10 feature: 알림톡 발송 부분의 목업 데이터 추가, 목업 API별로 대응되는 Query,Mutation훅 구현
  __mocks__/alimtalk.ts
  __mocks__/handler.ts
  app/actions/get-acceptance/index.ts
  app/actions/get-matching/index.ts
  app/actions/patch-displayname/index.ts
  app/actions/post-acceptance/index.ts
  app/actions/post-new-acceptance/index.ts
  app/hooks/mutation/index.ts
  app/hooks/mutation/usePatchMatchingDisplayname.ts
  app/hooks/mutation/usePoseMatchingAcceptance.ts
  app/hooks/mutation/usePostNewMatchingAcceptance.ts
  app/hooks/query/index.ts
  app/hooks/query/useGetAcceptance.ts
  app/hooks/query/useGetMatchingInfo.ts
  app/utils/httpService.ts
Labels: ⚙️ Setting, ✨ Feature

#11 docs: PR 템플릿에 테크스펙 링크 추가
  .github/pull_request_template.md
Labels: 📜 Docs

#12 feature: 모달 UI, useModal훅 구현
  app/(route)/layout.tsx
  app/(route)/page.tsx
  app/hooks/custom/index.ts
  app/hooks/custom/useClickoutside.ts
  app/hooks/custom/usemodal.ts
  app/hooks/mutation/index.ts
  app/hooks/mutation/usePostMatchingAcceptance.ts
  app/ui/Header.tsx
  app/ui/Modal.tsx
  app/ui/Sidebar.tsx
  app/ui/index.ts
  package-lock.json
Labels: ✨ Feature

#13 feat: 학부모 신청 내용 컴포넌트 구현
  __mocks__/browser.ts
  __mocks__/handler.ts
  __mocks__/init.ts
  __mocks__/parentsRequest.ts
  __mocks__/server.ts
  __tests__/example.test.tsx
  app/(route)/globals.css
  app/(route)/layout.tsx
  app/(route)/page.tsx
  app/actions/get-acceptance/index.ts
  app/actions/get-matching/index.ts
  app/actions/get-parents-request/index.ts
  app/actions/patch-displayname/index.ts
  app/components/root/ParentsRequest.tsx
  app/constants/parentsRequest.ts
  app/hooks/mutation/usePatchMatchingDisplayname.ts
  app/hooks/mutation/usePostMatchingAcceptance.ts
  app/hooks/mutation/usePostNewMatchingAcceptance.ts
  app/hooks/query/useGetAcceptance.ts
  app/hooks/query/useGetParentsRequest.ts
  app/providers/MSWProvider.tsx
  app/providers/QueryProvider.tsx
  app/providers/index.ts
  app/ui/Accordion.tsx
  app/ui/Header.tsx
  app/ui/Modal.tsx
  app/ui/Sidebar.tsx
  app/ui/TitleDesc.tsx
  app/ui/index.ts
  app/utils/instrumentation.ts
  jest.config.ts
  jest.setup.ts
  package.json
  yarn.lock
Labels: ✨ Feature

#14 Feat/teacher list
  __mocks__/handler.ts
  __mocks__/teacherList.ts
  app/(route)/layout.tsx
  app/(route)/page.tsx
  app/actions/get-teacher/index.ts
  app/actions/get-teachers/index.ts
  app/actions/patch-teacherModal/index.ts
  app/components/root/ParentsRequest.tsx
  app/components/root/TeacherList.tsx
  app/hooks/custom/useEditTeacherModal.ts
  app/hooks/mutation/index.ts
  app/hooks/mutation/usePatchTeacherModal.ts
  app/hooks/query/index.ts
  app/hooks/query/useGetTeachers.ts
  app/types/TeacherProfile.ts
  app/ui/Accordion.tsx
  app/ui/Columns/TeacherColumns.tsx
  app/ui/EditTeacherModal.tsx
  app/ui/Modal.tsx
  app/ui/Pagination.tsx
  app/ui/index.ts
  package.json
  public/images/youtube-icon.svg
  yarn.lock
Labels: ✨ Feature, 💅 Style

#15 Feature/notification 알림톡 발송 내역 마크업 구현
  __mocks__/alimtalk.ts
  __tests__/timeDifference.test.tsx
  app/(route)/[id]/(_components)/AlimHeader.tsx
  app/(route)/[id]/(_components)/AlimTable.tsx
  app/(route)/[id]/(constants)/AlimColumn.tsx
  app/(route)/[id]/(hooks)/useAlimTable.ts
  app/(route)/[id]/page.tsx
  app/actions/get-acceptance/index.ts
  app/actions/get-matching/index.ts
  app/actions/patch-displayname/index.ts
  app/hooks/custom/useClickoutside.ts
  app/hooks/query/useGetAcceptance.ts
  app/hooks/query/useGetMatchingInfo.ts
  app/ui/Header.tsx
  app/ui/Modal.tsx
  app/ui/Sidebar.tsx
Labels: ✨ Feature, 💅 Style

#16 Feat/teacher list filter 선생님 리스트 필터링 및 검색 마크업 구현
  app/(route)/page.tsx
  app/components/root/TeacherList.tsx
  app/components/root/TeacherListFilter.tsx
  app/components/root/TeacherListSearch.tsx
  app/constants/filterData.ts
  app/ui/CategoryFilter.tsx
  app/ui/Columns/TeacherColumns.tsx
  app/ui/RegionFilter.tsx
Labels: ✨ Feature, 💅 Style

#17 feat: 알림톡 발송 기능 구현
  __mocks__/alimtalk.ts
  __mocks__/teacherList.ts
  app/(route)/[id]/(_components)/Alim.tsx
  app/(route)/[id]/(_components)/AlimHeader.tsx
  app/(route)/[id]/(_components)/AlimTable.tsx
  app/(route)/[id]/(hooks)/useAlimTable.ts
  app/(route)/[id]/(hooks)/useAlimTable.tsx
  app/(route)/[id]/page.tsx
  app/actions/get-acceptance/index.ts
  app/actions/get-matching/index.ts
  app/actions/patch-displayname/index.ts
  app/actions/post-acceptance/index.ts
  app/actions/post-reacceptance/index.ts
  app/hooks/query/useGetAcceptance.ts
  app/hooks/query/useGetMatchingInfo.ts
  app/ui/Header.tsx
  app/ui/Modal.tsx
Labels: ✨ Feature

#18 Feat/parents list 학부모 리스트 컴포넌트 마크업 구축 및 폴더구조 변경
  app/(route)/[id]/(_components)/ParentsRequest.tsx
  app/(route)/[id]/(_components)/TeacherList.tsx
  app/(route)/[id]/(_components)/TeacherListFilter.tsx
  app/(route)/[id]/(_components)/TeacherListSearch.tsx
  app/(route)/[id]/page.tsx
  app/(route)/page.tsx
  app/components/root/ParentsList.tsx
  app/types/ParentsList.ts
  app/ui/Columns/ParentsColumns.tsx
  app/ui/Sidebar.tsx
Labels: ✨ Feature, 🛠️ Refactor, 💅 Style

#19 fix: 빌드 오류 해결
  .eslintrc.json
  .prettierrc
  app/(route)/[id]/(_components)/AlimHeader.tsx
  app/(route)/[id]/(_components)/TeacherList.tsx
  app/hooks/custom/useClickoutside.ts
  app/hooks/custom/useEditTeacherModal.ts
  app/ui/EditTeacherModal.tsx
  app/ui/Modal.tsx
Labels: 🐞BugFix, 🌍 Deploy

#20 feat: tanstack-table 페이지네이션 적용
  app/(route)/[id]/(_components)/Alim.tsx
  app/(route)/[id]/(_components)/AlimHeader.tsx
  app/(route)/[id]/(_components)/AlimTable.tsx
  app/(route)/[id]/(_components)/TeacherList.tsx
  app/(route)/[id]/(_components)/TeacherListSearch.tsx
  app/(route)/[id]/(constants)/AlimColumn.tsx
  app/(route)/[id]/(hooks)/useAlimTable.tsx
  app/(route)/[id]/page.tsx
  app/components/root/ParentsList.tsx
  app/ui/Header.tsx
Labels: ✨ Feature

#21 refactor: 폴더 구조 변경 (admin/teacher)
  app/(route)/(admin)/[id]/(_components)/Alim.tsx
  app/(route)/(admin)/[id]/(_components)/AlimHeader.tsx
  app/(route)/(admin)/[id]/(_components)/AlimTable.tsx
  app/(route)/(admin)/[id]/(_components)/ParentsRequest.tsx
  app/(route)/(admin)/[id]/(_components)/TeacherList.tsx
  app/(route)/(admin)/[id]/(_components)/TeacherListFilter.tsx
  app/(route)/(admin)/[id]/(_components)/TeacherListSearch.tsx
  app/(route)/(admin)/[id]/(constants)/AlimColumn.tsx
  app/(route)/(admin)/[id]/(hooks)/useAlimTable.tsx
  app/(route)/(admin)/[id]/page.tsx
  app/(route)/(admin)/layout.tsx
  app/(route)/(admin)/page.tsx
  app/(route)/(admin)/settle-management/page.tsx
  app/(route)/(admin)/teacher-management/page.tsx
  app/(route)/(teacher)/layout.tsx
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/(route)/layout.tsx
Labels: 🛠️ Refactor

#23 Feat/teacher list filter : 선생님 리스트 필터 기능 추가
  __mocks__/teacherList.ts
  app/(route)/(admin)/layout.tsx
  app/actions/get-teachers/index.ts
  app/components/root/Teacher.tsx
  app/components/root/TeacherList.tsx
  app/components/root/TeacherListFilter.tsx
  app/hooks/query/useGetTeachers.ts
  app/types/TeacherProfile.ts
  app/ui/CategoryFilter.tsx
  app/ui/Pagination.tsx
  app/ui/RegionFilter.tsx
Labels: ✨ Feature, 💅 Style

#25 feat: ProfileInfoBox 및 IconTitleChip 구현
  app/(route)/(teacher)/teacher/[id]/layout.tsx
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/components/teacher/IconTitleChip.tsx
  app/components/teacher/ProfileInfoBox.tsx
  app/constants/teacherStyle.ts
  public/images/solar_fire.png
Labels: ✨ Feature

#24 refactor: 쿼리 자동 무효화 도입 제안
  app/hooks/mutation/usePatchTeacherModal.ts
  app/providers/QueryProvider.tsx
  successInvalidDates..d.ts
Labels: ✨ Feature

#26 Feat/teacher list filter : 필터링 쿼리 방식 개선 및 검색어 필터 기능 추가
  __mocks__/teacherList.ts
  app/actions/get-teachers/index.ts
  app/components/root/Teacher.tsx
  app/components/root/TeacherList.tsx
  app/components/root/TeacherListFilter.tsx
  app/components/root/TeacherListSearch.tsx
  app/hooks/query/useGetTeachers.ts
Labels: ✨ Feature

#27 feat: MatchingModal UI 구현
  app/components/teacher/MatchingModal.tsx
  app/ui/Modal.tsx
Labels: ✨ Feature

#28 refactor: use-server구문 제거, postman mock server로 경로 변경
  __tests__/example.test.tsx
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/actions/get-acceptance/index.ts
  app/actions/get-matching/index.ts
  app/actions/get-parents-request/index.ts
  app/actions/patch-displayname/index.ts
  app/actions/post-acceptance/index.ts
  app/components/root/TeacherListSearch.tsx
  app/components/teacher/IconTitleChip.tsx
  app/constants/teacherStyle.ts
  app/utils/httpService.ts
Labels: ⚙️ Setting

#29 fix: 선생님 지도스타일 enum값 변경 및 아이콘 추가
  app/(route)/(teacher)/teacher/[id]/page.tsx
  app/constants/teacherStyle.ts
  public/images/Eyes.png
  public/images/Fire.png
  public/images/Guard.png
  public/images/Note.png
  public/images/Warm.png
  public/images/Write.png
  public/images/solar_fire.png
Labels: 🛠️ Refactor, 💅 Style

#30 bugfix: use server 다시 추가, search 관련 코드 추가, 소소한 오타수정
  app/actions/get-acceptance/index.ts
  app/actions/get-matching/index.ts
  app/actions/get-parents-request/index.ts
  app/actions/get-teachers/index.ts
  app/actions/patch-displayname/index.ts
  app/actions/patch-teacherModal/index.ts
  app/actions/post-acceptance/index.ts
  app/actions/post-new-acceptance/index.ts
  app/components/root/TeacherListSearch.tsx
Labels: 🐞BugFix

#31 feat: DividerList 구현 및 ProfileInfoBox props 타입 변경
  app/components/teacher/ProfileInfoBox.tsx
  app/data/teacherDetailClass.json
  app/data/teacherDetailMain.json
  app/ui/DividerList.tsx
  tailwind.config.js
Labels: ✨ Feature, 🛠️ Refactor, 💅 Style
