Repository Y-edu/Y-edu-front, pull requests merged in 2025-05, with the labels that each got.

#162 Fix/timetable bh qa : 매칭 수락/거절 페이지 타임테이블 로딩표시 추가
  app/(route)/(teacher)/teacher/notify/[token]/select-time/page.tsx
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
Labels: 🐞BugFix

#163 Feat/update guide timetable
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TimeTable/GuideTimeTable.tsx
  app/components/teacher/TimeTable/index.tsx
Labels: 🐞BugFix, ✨ Feature

#164 fix: 가능시간 유도 알림톡 타임테이블 기능 수정
  app/(route)/(teachersetting)/teachersetting/time/page.tsx
  app/actions/get-teacher-setting-time-by-token/index.ts
  app/components/teacher/TimeTable/useTimeTable.ts
  app/hooks/query/useGetTeacherSettingTimeByToken.ts
Labels: 🐞BugFix, ✨ Feature

#165 fix: 매칭 수락/거절 페이지 타임테이블 헤더 텍스트 수정
  app/(route)/(teacher)/teacher/notify/[token]/select-time/page.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
Labels: 💅 Style

#167 fix: 셀 1칸 선택 기준 60분으로 수정
  app/components/teacher/TimeTable/useTimeTable.ts
Labels: 🚨 Hotfix

#169 fix: 지역 설정 페이지도 시간설정 페이지와 디자인 통일
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
Labels: 💅 Style

#171 refactor: 폴더 구조 정리
  app/(route)/(teacher)/teacher/sample/page.tsx
  app/components/admin/TeacherList.tsx
  app/components/teacher/TeacherDetail/TeacherDetailMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/ui/Box/SettingBox.tsx
  app/ui/Box/ToggleBox.tsx
  app/ui/Modal/Modal.tsx
  app/ui/Modal/TeacherUpdateModal.tsx
  app/ui/Switch/ToggleSwitch.tsx
  app/ui/index.ts
Labels: 🛠️ Refactor

#170 feat: 선생님 수업 완료 카드 컴포넌트 코드 작성
  app/ui/Card/ClassScheduleCard.tsx
Labels: ✨ Feature

#172 feat: Chip 컴포넌트 구현 + 아이콘 버튼 컴포넌트 예시
  app/(route)/(teacher)/teacher/session-complete/page.tsx
  app/components/result/ConfirmedResult/index.tsx
  app/components/result/DayBtn.tsx
  app/ui/Chip/index.tsx
  public/images/calendar.svg
  public/images/person-img.png
Labels: ✨ Feature

#173 Feat/session finish component : 과외 일정(sessionSchedule) 목록 화면 구현
  app/(route)/(teacher)/teacher/session-schedule/page.tsx
  app/actions/post-getSessions/index.ts
  app/components/result/HeaderWithBack.tsx
  app/components/teacher/SessionSchedule/index.tsx
  app/components/teacher/SessionSchedule/useSessionSchedule.ts
  app/hooks/query/useGetSessions.ts
  app/ui/Bar/TabBar.tsx
  app/ui/Card/SessionScheduleCard/ActionButtons.ts
  app/ui/Card/SessionScheduleCard/index.tsx
Labels: ✨ Feature, 💅 Style

#175 feat: 기존 일정 없을 때 과외 완료 페이지 + '전체 일정 변경' 페이지 구현
  app/(route)/(teacher)/teacher/session-change/page.tsx
  app/(route)/(teacher)/teacher/session-complete/page.tsx
  app/actions/get-schedules/index.ts
  app/actions/put-schedules/index.ts
  app/components/teacher/Session/SessionSchedule.tsx
  app/components/teacher/Session/useSessionSchedule.ts
  app/hooks/mutation/usePutSchedules.ts
  app/hooks/query/useGetSchedules.ts
Labels: ✨ Feature

#176 feat: 과외 완료 기능 구현
  app/(route)/(teacher)/teacher/session-complete/page.tsx
  app/actions/get-session-by-token/index.ts
  app/actions/patch-sessions/index.ts
  app/components/result/ConfirmedResult/index.tsx
  app/components/result/DivWithLabel.tsx
  app/components/result/HeaderWithBack.tsx
  app/components/teacher/Session/SessionComplete.tsx
  app/components/teacher/Session/SessionSchedule.tsx
  app/components/teacher/SessionSchedule/index.tsx
  app/constants/session/homework.ts
  app/hooks/mutation/usePatchSessions.ts
  app/hooks/query/useGetSessionByToken.ts
  app/ui/Radio/index.tsx
  app/utils/getDayOfWeek.ts
Labels: ✨ Feature

#179 Feat/session complete view review
  app/(route)/(teacher)/teacher/session-review/page.tsx
  app/components/teacher/Session/SessionReviewView.tsx
  app/ui/Radio/index.tsx
Labels: ✨ Feature

#181 hotfix: duration 90분 추가
  app/components/result/TimePicker/index.tsx
Labels: 🚨 Hotfix

#180 Fix/session schedule list : 각 탭별 '전체 일정 변경' 기능 오류 수정. 이에 따른 자잘한 코드 수정
  app/(route)/(teacher)/teacher/session-change/page.tsx
  app/(route)/(teacher)/teacher/session-complete/page.tsx
  app/(route)/(teacher)/teacher/session-schedule/page.tsx
  app/actions/get-schedules/index.ts
  app/actions/put-schedules/index.ts
  app/components/teacher/Session/SessionSchedule.tsx
  app/components/teacher/Session/useSessionSchedule.ts
  app/components/teacher/SessionList/index.tsx
  app/hooks/mutation/usePatchSessions.ts
  app/hooks/mutation/usePutSchedules.ts
  app/hooks/query/useGetSchedules.ts
Labels: ✨ Feature

#183 Feat/collect data
  app/components/teacher/Session/SessionComplete.tsx
  app/utils/mixpanel.ts
Labels: ✨ Feature

#184 Fix/session list bh qa : 카드 style 변경 및 기능 오류 수정
  app/(route)/(teacher)/teacher/session-change/page.tsx
  app/(route)/(teacher)/teacher/session-complete/page.tsx
  app/(route)/(teacher)/teacher/session-review/page.tsx
  app/(route)/(teacher)/teacher/session-schedule/page.tsx
  app/components/teacher/Session/useSessionSchedule.ts
  app/components/teacher/SessionList/index.tsx
  app/components/teacher/SessionList/useSessionList.ts
  app/hooks/mutation/usePatchSessions.ts
  app/ui/Bar/TabBar.tsx
  app/ui/Card/SessionListCard/index.tsx
Labels: 🐞BugFix, 💅 Style

#186 Fix/session list bh qa : 코드리뷰 반영
  app/(route)/(teacher)/teacher/session-change/page.tsx
  app/(route)/(teacher)/teacher/session-schedule/page.tsx
  app/components/teacher/SessionList/index.tsx
Labels: 🐞BugFix

#185 Fix/qa
  app/components/result/ConfirmedResult/useConfirmedResult.ts
  app/components/result/FirstDayPicker/index.tsx
  app/components/result/FirstDayPicker/useFirstDayPicker.ts
  app/components/result/HeaderWithBack.tsx
  app/components/teacher/SessionList/RescheduleSheet.tsx
  app/hooks/mutation/usePatchSessions.ts
  app/ui/Card/SessionListCard/index.tsx
  app/utils/getErrorMessage.ts
  app/utils/httpService.ts
Labels: ✨ Feature

#187 fix: 완료톡 쌓기 자동화 QA 작업
  app/(route)/(teacher)/teacher/session-complete/page.tsx
  app/actions/get-session-by-token/index.ts
  app/components/result/TimePicker/index.tsx
  app/components/teacher/Session/SessionComplete.tsx
  app/components/teacher/Session/SessionSchedule.tsx
  app/components/teacher/Session/useSessionSchedule.ts
  app/ui/Textarea/index.tsx
Labels: 🐞BugFix

#188 Fix/bh bugfix : 완료톡 스프린트 QA 동작 오류 수정, 학부모 타임테이블 중복제출 방지 코드 추가
  app/components/teacher/TeacherDetail/TeacherDetailChooseTime.tsx
  app/components/teacher/TimeTable/useTimeTable.ts
  app/ui/BottomSheet/index.tsx
  app/ui/Card/SessionListCard/index.tsx
Labels: 🐞BugFix

#189 Fix/tabcomponent style : 탭바 컴포넌트 스타일 변경
  app/(route)/(teacher)/teacher/session-schedule/page.tsx
  app/components/teacher/SessionList/index.tsx
  app/ui/Bar/TabBar.tsx
Labels: 💅 Style

#191 fix: 탭 x축 스크롤 시 왼쪽 마진값이 0이 되어버리는 오류 해결
  app/(route)/(teacher)/teacher/session-schedule/page.tsx
Labels: 🐞BugFix

#193 fix: 변경된 dto 반영
  app/(route)/(teacher)/teacher/session-complete/page.tsx
  app/actions/post-getSessions/index.ts
Labels: 🐞BugFix

#194 fix: 스케줄 없을 경우 버그 수정, 토큰 무효시 리다이렉트 추가
  app/(route)/(teacher)/teacher/session-complete/page.tsx
Labels: 🐞BugFix

#195 fix: sessionScheduleList header 텍스트 수정
  app/(route)/(teacher)/teacher/session-schedule/page.tsx
Labels: ✨ Feature

#196 feat: 수업관리 탭 UI 개발
  app/(route)/(admin)/zuzuclubadmin/class-management/[formId]/page.tsx
  app/(route)/(admin)/zuzuclubadmin/class-management/page.tsx
  app/(route)/(admin)/zuzuclubadmin/settle-management/page.tsx
  app/actions/get-class-info/index.ts
  app/components/admin/ClassDetailList.tsx
  app/components/admin/ClassList.tsx
  app/ui/Bar/Sidebar.tsx
  app/ui/Columns/ClassColumns.tsx
  app/ui/Columns/ClassDetailColumns.tsx
Labels: ✨ Feature

#197 feat: 믹스패널 리뷰 전송 이벤트 속성 추가
  app/(route)/(teacher)/teacher/session-complete/page.tsx
  app/components/teacher/Session/SessionComplete.tsx
Labels: ✨ Feature

#199 Feat/admin 수업관리 목록/상세 조회, 수업 상태변경
  app/(route)/(admin)/zuzuclubadmin/class-management/[formId]/page.tsx
  app/(route)/(admin)/zuzuclubadmin/class-management/[matchingId]/page.tsx
  app/(route)/(admin)/zuzuclubadmin/class-management/page.tsx
  app/(route)/layout.tsx
  app/actions/get-class-info/index.ts
  app/actions/graphql/class-management.ts
  app/components/admin/ClassDetailList.tsx
  app/components/admin/ClassList.tsx
  app/hooks/query/useGetClassList.ts
  app/providers/ApolloClient.tsx
  app/ui/Columns/ClassColumns.tsx
  app/ui/Columns/ClassDetailColumns.tsx
  package.json
  yarn.lock
Labels: ✨ Feature
