Repository Y-edu/Y-edu-front, pull requests merged in 2025-06, with the labels that each got.

#200 fix:링크에 토큰만 있는 과외완료 페이지에서 뒤로가기 버튼 클릭 시 탭 지정 안되는 오류 해결
  app/(route)/(teacher)/teacher/session-complete/page.tsx
Labels: 🐞BugFix

#204 Fix/byunghoon ut : 3차 페이지네이션 적용 및 무한 스크롤 구현,
  app/(route)/(teacher)/teacher/session-complete/page.tsx
  app/(route)/(teacher)/teacher/session-review/page.tsx
  app/(route)/(teacher)/teacher/session-schedule/page.tsx
  app/actions/post-getSessions/index.ts
  app/components/teacher/SessionList/index.tsx
  app/hooks/mutation/usePatchSessions.ts
  app/hooks/query/useGetSessions.ts
Labels: 🐞BugFix, ✨ Feature

#206 fix: 백엔드 sorting 변경으로 프론트 코드 제거
  app/components/teacher/SessionList/useSessionList.ts
Labels: 🛠️ Refactor

#207 [fix] 이미 있는 일정으로 변경하려고 할 때 막기 + 최대 너비 수정
  app/(route)/(teacher)/layout.tsx
  app/components/teacher/Session/SessionComplete.tsx
  app/components/teacher/Session/SessionSchedule.tsx
  app/components/teacher/SessionList/RescheduleSheet.tsx
Labels: 🐞BugFix, 💅 Style

#208 fix: getSchedules 캐시 무효화로 정규 일정 변경시 목록에 바로 반영되지 않는 오류 해결.
  app/hooks/query/useGetSessions.ts
Labels: 🐞BugFix

#209 fix: teacherStyle 속성에 nullable 추가
  app/actions/get-parents-request/index.ts
Labels: 🚨 Hotfix

#211 fix: 타입오류 수정
  app/actions/get-tutoring/index.ts
Labels: 🚨 Hotfix

#213 Fix/byunghoon ut : QA 오류 수정
  app/(route)/(teacher)/teacher/session-complete/page.tsx
  app/components/teacher/SessionList/useSessionList.ts
Labels: 🐞BugFix

#215 [style] QA - 스타일 수정
  app/components/teacher/MatchingInfo.tsx
  app/ui/BottomSheet/index.tsx
Labels: 💅 Style

#216 fix: 쿼리 무효화로 sessions 데이터 갱신
  app/hooks/mutation/usePutSchedules.ts
Labels: 🐞BugFix

#217 fix:과외일정 목록 페이지 텍스트 수정
  app/(route)/(teacher)/teacher/session-schedule/page.tsx
Labels: 💅 Style

#218 fix: 완료 이후 미완료 리페칭 문제 수정
  app/hooks/mutation/usePatchSessions.ts
Labels: 🐞BugFix

#220 fix: 날짜변경 시트에서 시간 같은지 비교하는 코드 제거
  app/components/teacher/SessionList/RescheduleSheet.tsx
Labels: 🐞BugFix

#222 fix: 학부모 가능시간 텍스트 형태로 수정
  app/actions/get-tutoring/index.ts
  app/components/teacher/MatchingInfo.tsx
  app/components/teacher/MatchingProposal.tsx
Labels: 🐞BugFix

#224 fix: wantedTime nullable 처리
  app/actions/get-tutoring/index.ts
  app/components/teacher/MatchingProposal.tsx
Labels: 🚨 Hotfix
