Repository Y-edu/Y-edu-front, pull requests merged in 2025-03, with the labels that each got.

#90 fix: 알림테이블 프로필 상세보기 컬럼에서 버튼 외 영역 클릭 시 해당 행 체크되지 않도록 수정
  app/components/admin/AlimColumn.tsx
  app/components/admin/AlimTable.tsx
Labels: 💅 Style

#93 fix : 어드민에서 알림톡 상태에 따라 정렬하는 구문 추가
  app/(route)/(admin)/zuzuclubadmin/[id]/(hooks)/useAlimTable.tsx
  app/components/admin/AlimColumn.tsx
Labels: ✨ Feature

#95 fix : 알림톡 발송 분을 일 + 시간 + 분으로 포맷하는 함수 구현
  app/components/admin/AlimHeader.tsx
  app/utils/formatTimetoDate.ts
Labels: ✨ Feature

#97 fix: 테이블 반응형으로 줄지 않고 스크롤되도록 변경
  app/(route)/(admin)/zuzuclubadmin/[id]/page.tsx
  app/ui/Bar/Sidebar.tsx
Labels: 💅 Style

#99 add: 선생님 리스트 테이블에 성별 컬럼 추가
  app/actions/get-teacher-search/index.ts
  app/ui/Columns/TeacherColumns.tsx
Labels: ✨ Feature, 💅 Style

#98 feat: 선생님 과외 설정 페이지 폴더구조 설정, 메인페이지 마크업 코드 작성
  app/(route)/(teachersetting)/teachersetting/[id]/[phone]/page.tsx
  app/(route)/(teachersetting)/teachersetting/[id]/[phone]/region/page.tsx
  app/(route)/(teachersetting)/teachersetting/[id]/[phone]/time/page.tsx
  app/(route)/(teachersetting)/teachersetting/layout.tsx
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/ui/Box/SettingBox.tsx
Labels: ⚙️ Setting, ✨ Feature, 💅 Style

#103 feat: 과외 가능지역 페이지 마크업 코드 작성
  app/(route)/(teachersetting)/teachersetting/[id]/[phone]/region/page.tsx
  app/components/teacher/ProfileInfoBox.tsx
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
  app/constants/buttonLabels.ts
  app/ui/Box/SettingBox.tsx
  app/ui/List/BulletList.tsx
  app/ui/ToggleSwitch.tsx
  public/images/arrow-black.png
Labels: ✨ Feature, 💅 Style

#104 refactor: 폴더 구조 변경 / feat: 세팅 메인페이지 및 지역 페이지 데이터 조회 api 적용.
  app/(route)/(teachersetting)/teachersetting/login/page.tsx
  app/(route)/(teachersetting)/teachersetting/page.tsx
  app/(route)/(teachersetting)/teachersetting/region/page.tsx
  app/(route)/(teachersetting)/teachersetting/time/page.tsx
  app/actions/get-teacher-setting-info/index.ts
  app/actions/patch-teacher-setting-alarmtalk/index.tsx
  app/actions/patch-teacher-setting-region/index.tsx
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
  app/hooks/mutation/usePatchTeacherSettingAlarmTalk.ts
  app/hooks/mutation/usePatchTeacherSettingRegion.ts
  app/hooks/query/useGetTeacherSettingInfo.ts
Labels: ✨ Feature, 🛠️ Refactor

#105 Feat/teacher schedule setting / 로그인 기능 구현, MUI 로딩 적용, 지역페이지 하단 버튼 고정
  app/(route)/(teachersetting)/teachersetting/login/page.tsx
  app/(route)/(teachersetting)/teachersetting/page.tsx
  app/(route)/(teachersetting)/teachersetting/region/page.tsx
  app/components/teacher/TeacherSetting/TeacherSettingLogin.tsx
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
  app/hooks/query/useGetTeacherSettingInfo.ts
  package.json
  yarn.lock
Labels: ✨ Feature, 💅 Style

#106 fix: 페이지 ErrorBoundary 처리, 카카오채널 링크 변경, 자잘한 스타일수정
  app/(route)/(teachersetting)/teachersetting/login/page.tsx
  app/(route)/(teachersetting)/teachersetting/page.tsx
  app/(route)/(teachersetting)/teachersetting/region/page.tsx
  app/components/root/main.tsx
  app/components/teacher/TeacherSetting/TeacherSettingLogin.tsx
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
  app/ui/ErrorUI.tsx
Labels: 🛠️ Refactor, 💅 Style

#107 feat: 과외건 공지 받기 토글 끌 때 모달창 추가
  app/components/teacher/MatchingModal.tsx
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/ui/Modal.tsx
Labels: ✨ Feature, 💅 Style

#109 feat : 선생님 변경 시간 수정 API 훅 구현, 이미 선택된 시간에도 취소 가능하게 타임테이블 컴포넌트 수정
  app/(route)/(teachersetting)/teachersetting/time/page.tsx
  app/actions/put-teacher-avaiable/index.ts
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TeacherSetting/TimeTable.tsx
  app/hooks/mutation/usePutAvaiableTeacherTime.ts
  app/utils/date.ts
Labels: ✨ Feature

#108 타임테이블 컴포넌트 시간 추가 구현
  app/(route)/(teachersetting)/teachersetting/time/page.tsx
  app/actions/put-teacher-avaiable/index.ts
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TeacherSetting/TimeTable.tsx
  app/hooks/mutation/usePutAvaiableTeacherTime.ts
  app/utils/date.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: ✨ Feature

#111 Feat/teacher schedule setting : 시간 설정 페이지 searchParams 제거, localstorage 이용 구조로 변경
  app/(route)/(teachersetting)/teachersetting/time/page.tsx
  app/components/teacher/TeacherSetting/TeacherSettingLogin.tsx
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TeacherSetting/TimeTable.tsx
Labels: 🛠️ Refactor, 💅 Style

#112 add: 시간 설정 페이지 상단에 기능 관련 공지 문구 추가
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TeacherSetting/TimeTable.tsx
Labels: 💅 Style

#113 add: 변경사항 있을 때 뒤로가기,새로고침 등 브라우저 경고창 추가
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TeacherSetting/TimeTable.tsx
  app/hooks/custom/useUnsavedChangeWarning.ts
Labels: ✨ Feature

#114 fix: 초기 렌더링 시 data가 없을 때 Error페이지 렌더링 되는 문제 해결
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingProvider.tsx
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
Labels: 🐞BugFix

#115 Feat/teacher schedule setting : QA 변경사항 반영
  app/components/teacher/TeacherSetting/TeacherSettingMain.tsx
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TeacherSetting/TimeTable.tsx
Labels: ✨ Feature, 💅 Style

#117 add: 변경사항 저장하지 않고 뒤로가기 누를 때 경고 모달 추가
  app/(route)/(teachersetting)/teachersetting/time/page.tsx
  app/components/teacher/TeacherSetting/TeacherSettingRegion.tsx
  app/components/teacher/TeacherSetting/TeacherSettingTime.tsx
  app/components/teacher/TeacherSetting/TimeTable.tsx
  app/hooks/custom/useUnsavedBackWarning.ts
  app/hooks/custom/useUnsavedChangeWarning.ts
Labels: ✨ Feature
