Repository Y-edu/Y-edu-front, pull requests merged in 2025-08, with the labels that each got.

#254 fix: 수업 시간 라벨 텍스트 수정
  app/components/result/ConfirmedResult/index.tsx
  app/components/result/DivWithLabel.tsx
Labels: 💅 Style

#255 fix: 매칭 상태 '전송'인 선생님한테만 '이 선생님과 할래요' 가능하게 변경
  app/components/admin/AlimHeader.tsx
Labels: 🐞BugFix

#256 fix: 이 선생님과 할래요 버튼 disabled 로직 수정
  app/components/admin/AlimHeader.tsx
Labels: 🐞BugFix

#257 [feat] 완료된 수업리뷰 페이지에 수업 시간 추가
  app/(route)/(teacher)/teacher/session-review/page.tsx
  app/actions/get-sessions-month/index.ts
  app/components/teacher/Session/SessionReviewView.tsx
  app/hooks/query/useGetSessionsMonth.ts
  public/images/icon_arrow.svg
Labels: ✨ Feature

#261 [feat] 선생님 수업관리 페이지 수정사항 반영
  app/(route)/(teacher)/teacher/session-schedule/page.tsx
  app/actions/get-sessions-month/index.ts
  app/components/teacher/Session/MonthDurationNavigator.tsx
  app/components/teacher/SessionList/index.tsx
  app/components/teacher/SessionList/useSessionList.ts
  app/hooks/mutation/usePatchSessions.ts
  app/ui/Card/SessionListCard/index.tsx
  app/ui/Select/index.tsx
  app/ui/index.ts
Labels: 🐞BugFix, ✨ Feature

#262 fix: 무료보강일 때는 휴강 버튼 제거
  app/components/teacher/SessionList/useSessionList.ts
Labels: ✨ Feature

#263 fix: classMinute null이면 안 보이게 처리
  app/ui/Card/SessionListCard/index.tsx
Labels: 🐞BugFix

#266 [feat] 수업관리 탭 결제 요청 기능 추가 & 테이블 변경
  __mocks__/handler.ts
  __mocks__/payment.ts
  app/(route)/(admin)/zuzuclubadmin/class-management/page.tsx
  app/actions/graphql/class-management.ts
  app/actions/post-payment-request/index.ts
  app/components/admin/ClassList.tsx
  app/hooks/query/useGetClassList.ts
  app/providers/MSWProvider.tsx
  app/ui/Bar/SearchBar.tsx
  app/ui/Columns/ClassColumns.tsx
  app/utils/httpService.ts
Labels: ✨ Feature

#267 fix: 주 n회 a분으로 수업 시수 변경 (graphql 필드 변경)
  app/actions/graphql/class-management.ts
  app/hooks/query/useGetClassList.ts
  app/ui/Columns/ClassColumns.tsx
Labels: 🐞BugFix
